### ISSUE TITLE
Change engine to node-sqlite3

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js-sqlite#3]
I would like to suggest changing the engine from [kripten sql.js](https://github.com/kripken/sql.js) to [node-sqlite3](https://github.com/mapbox/node-sqlite3).

According to kripten sql.js' [documentation](https://github.com/kripken/sql.js/blob/master/README.md):
```
It uses a virtual database file stored in memory, and thus doesn't persist the changes made 
to the database.  However, it allows you to import any existing sqlite file, and to export the 
created database as a javascript typed array.
```
[Node-sqlite3](https://github.com/mapbox/node-sqlite3) does persist changes made to the database and also supports *in-memory* databases - something desired and requested by the [issue 2](https://github.com/mlaanderson/database-js-sqlite/issues/2):
```javascript
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');
...
```

**Comment by mlaanderson** [comment]
node-sqlite3 is not currently building for Mac OS and on Windows appears to require Visual Studio 2015. It doesn't build on Windows 10 with Visual Studio 2017. This limits the usefulness of the library. Until that is more reliable, this project will have to stay with sql.js

**Comment by thiagodp** [comment]
You're right, that's really important - I hadn't observed node-sqlite3's dependencies.
